CREATE PROCEDURE A11
AS
BEGIN

--DROP FOREIGN KEYS
ALTER TABLE FACT_TABLE DROP CONSTRAINT FK_FACT_PILOTDIM
ALTER TABLE FACT_TABLE DROP CONSTRAINT FK_FACT_AIRCRAFTDIM
ALTER TABLE FACT_TABLE DROP CONSTRAINT FK_FACT_TIMEDIM

--TRUNCATE TABLES
TRUNCATE TABLE FACT_TABLE
TRUNCATE TABLE PILOTDIM
TRUNCATE TABLE AIRCRAFTDIM
TRUNCATE TABLE TIMEDIM
TRUNCATE TABLE STAGING

--REINSERT FOREIGN KEYS
ALTER TABLE FACT_TABLE
ADD CONSTRAINT FK_FACT_PILOTDIM FOREIGN KEY (PILOT_ID) REFERENCES PILOTDIM (PILOT_ID);
ALTER TABLE FACT_TABLE
ADD CONSTRAINT FK_FACT_AIRCRAFTDIM FOREIGN KEY (AIRCRAFT_ID) REFERENCES AIRCRAFTDIM (AIRCRAFT_ID);
ALTER TABLE FACT_TABLE
ADD CONSTRAINT FK_FACT_TIMEDIM FOREIGN KEY (TIME_ID) REFERENCES TIMEDIM (TIME_ID);

--POPULATE DIMENSION AND STAGING TABLES
INSERT INTO PILOTDIM (EMP_NUM, EMP_LNAME, EMP_FNAME, PIL_LICENSE, PIL_RATINGS, PIL_MED_TYPE, PIL_MED_DATE, PIL_PT135_DATE)
SELECT P.EMP_NUM, EMP_LNAME, EMP_FNAME, PIL_LICENSE, PIL_RATINGS, PIL_MED_TYPE, PIL_MED_DATE, PIL_PT135_DATE
FROM PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM

INSERT INTO TIMEDIM (CHAR_DATE, MONTH, YEAR)
SELECT CHAR_DATE, MONTH(CHAR_DATE) AS MONTH, YEAR(CHAR_DATE) AS YEAR
FROM CHARTER

INSERT INTO AIRCRAFTDIM (MOD_CODE, AC_NUMBER, AC_TTAF, AC_TTEL, AC_TTER)
SELECT MOD_CODE, AC_NUMBER, AC_TTAF, AC_TTEL, AC_TTER
FROM AIRCRAFT

INSERT INTO STAGING (EMP_NUM, EMP_LNAME, EMP_FNAME, MOD_CODE, AC_NUMBER, CHAR_DATE,
FUEL_USED, DISTANCE, REVENUE)
SELECT P.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, M.MOD_CODE, M.MOD_NAME, C.CHAR_DATE,
C.CHAR_FUEL_GALLONS, C.CHAR_DISTANCE, SUM(C.CHAR_FUEL_GALLONS * M.MOD_CHG_MILE) AS
REVENUE
FROM PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM
INNER JOIN CREW CW ON CW.EMP_NUM = E.EMP_NUM
INNER JOIN CHARTER C ON C.CHAR_TRIP = CW.CHAR_TRIP
INNER JOIN AIRCRAFT A ON A.AC_NUMBER = C.AC_NUMBER
INNER JOIN MODEL M ON M.MOD_CODE = A.MOD_CODE
GROUP BY P.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, M.MOD_CODE, M.MOD_NAME, C.CHAR_DATE,
C.CHAR_FUEL_GALLONS, C.CHAR_DISTANCE

--UPDATE DW KEYS
UPDATE STAGING
SET PILOT_ID = P.PILOT_ID
FROM STAGING S INNER JOIN PILOTDIM P ON S.EMP_NUM = P.EMP_NUM
UPDATE STAGING
SET AIRCRAFT_ID = T.AIRCRAFT_ID
FROM STAGING S INNER JOIN AIRCRAFTDIM T ON S.MOD_CODE = T.MOD_CODE
UPDATE STAGING
SET TIME_ID = T.TIME_ID
FROM STAGING S INNER JOIN TIMEDIM T ON S.CHAR_DATE = T.CHAR_DATE

--POPULATE FACT TABLE
INSERT INTO FACT_TABLE (PILOT_ID, AIRCRAFT_ID, TIME_ID, FUEL_USED, DISTANCE, REVENUE)
SELECT PILOT_ID, AIRCRAFT_ID, TIME_ID, FUEL_USED, DISTANCE, REVENUE
FROM STAGING
END

EXEC A11
